#!/bin/bash
# bundle_filters.sh - Download and pin filter lists for bundling in APK
#
# PURPOSE:
#   Pre-release preparation script. Downloads filter lists and records
#   their exact source versions in filter_versions.json so that both
#   our CI build and F-Droid's build produce identical APKs.
#
# USAGE:
#   ./scripts/bundle_filters.sh
#   ./scripts/bundle_filters.sh --stevenblack-commit <sha>
#
# Run this script BEFORE tagging a release, then commit the results:
#   ./scripts/bundle_filters.sh
#   git add app/src/main/assets/bundled_filters/ scripts/filter_versions.json
#   git commit -m "Update bundled filter lists"

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$PROJECT_DIR/app/src/main/assets/bundled_filters"
VERSIONS_FILE="$SCRIPT_DIR/filter_versions.json"

mkdir -p "$OUTPUT_DIR"

# Parse arguments
STEVENBLACK_COMMIT=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stevenblack-commit)
            STEVENBLACK_COMMIT="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            echo "Usage: $0 [--stevenblack-commit <sha>]"
            exit 1
            ;;
    esac
done

# Filter list definitions
# Filenames = Java String.hashCode() of the original URL
EASYLIST_URL="https://easylist.to/easylist/easylist.txt"
EASYPRIVACY_URL="https://easylist.to/easylist/easyprivacy.txt"

if [ -n "$STEVENBLACK_COMMIT" ]; then
    STEVENBLACK_URL="https://raw.githubusercontent.com/StevenBlack/hosts/$STEVENBLACK_COMMIT/hosts"
else
    # Default: resolve latest commit on master for pinning
    echo "Resolving latest StevenBlack commit..."
    STEVENBLACK_COMMIT=$(curl -sI "https://api.github.com/repos/StevenBlack/hosts/commits/master" \
        | grep -i "^x-github-request-id" > /dev/null && \
        curl -s "https://api.github.com/repos/StevenBlack/hosts/commits/master" \
        | grep '"sha"' | head -1 | sed 's/.*"sha": *"\([^"]*\)".*/\1/')
    if [ -z "$STEVENBLACK_COMMIT" ]; then
        echo "Warning: Could not resolve StevenBlack commit SHA, using 'master'"
        STEVENBLACK_COMMIT="master"
    fi
    STEVENBLACK_URL="https://raw.githubusercontent.com/StevenBlack/hosts/$STEVENBLACK_COMMIT/hosts"
fi

# Download each filter list explicitly (avoid associative arrays with keys starting with -)
DOWNLOAD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

download_filter() {
    local filename="$1"
    local url="$2"
    echo "Downloading: $url"
    echo "  -> $OUTPUT_DIR/$filename"
    curl -sL -o "$OUTPUT_DIR/$filename" "$url"
    size=$(du -h "$OUTPUT_DIR/$filename" | cut -f1)
    echo "  OK ($size)"
}

download_filter "-1025149380.txt" "$EASYLIST_URL"
download_filter "-1463595922.txt" "$EASYPRIVACY_URL"
download_filter "320624723.txt" "$STEVENBLACK_URL"


# Strip comments and blank lines to reduce size (keep only domain lines)
echo ""
echo "Stripping comments from EasyList and EasyPrivacy..."
for f in "$OUTPUT_DIR/-1025149380.txt" "$OUTPUT_DIR/-1463595922.txt"; do
    if [ -f "$f" ]; then
        original_size=$(du -h "$f" | cut -f1)
        # Remove comment lines (starting with ! or [) and blank lines
        sed -i.bak '/^[!\[]/d; /^$/d; /^#/d' "$f" && rm -f "$f.bak"
        new_size=$(du -h "$f" | cut -f1)
        echo "  $(basename "$f"): $original_size -> $new_size"
    fi
done

echo "Stripping comments from StevenBlack hosts..."
f="$OUTPUT_DIR/320624723.txt"
if [ -f "$f" ]; then
    original_size=$(du -h "$f" | cut -f1)
    sed -i.bak '/^#/d; /^$/d' "$f" && rm -f "$f.bak"
    new_size=$(du -h "$f" | cut -f1)
    echo "  $(basename "$f"): $original_size -> $new_size"
fi

# Write version manifest
cat > "$VERSIONS_FILE" <<EOF
{
  "description": "Pinned versions of bundled filter lists. Generated by scripts/bundle_filters.sh",
  "downloaded_at": "$DOWNLOAD_DATE",
  "filters": {
    "-1025149380.txt": {
      "name": "EasyList",
      "url": "$EASYLIST_URL"
    },
    "-1463595922.txt": {
      "name": "EasyPrivacy",
      "url": "$EASYPRIVACY_URL"
    },
    "320624723.txt": {
      "name": "StevenBlack Hosts",
      "url": "$STEVENBLACK_URL",
      "commit": "$STEVENBLACK_COMMIT"
    }
  }
}
EOF

echo ""
echo "Done! Filter lists saved to $OUTPUT_DIR"
ls -lh "$OUTPUT_DIR"
echo ""
echo "Version manifest written to $VERSIONS_FILE"
echo ""
echo "Next steps:"
echo "  git add app/src/main/assets/bundled_filters/ scripts/filter_versions.json"
echo "  git commit -m 'Update bundled filter lists'"
